apiVersion: v1
kind: Service

metadata:
  name: ncpl-service
  namespace: java-app

spec:
  selector:
    app: ncpl

  ports:
  - protocol: TCP
    port: 80
    targetPort: 8080

  type: LoadBalancer
